# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghostable" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "9fd2c9c4ffb47f5c838df852af9736100ce5d3c040425fae4213755e24ff9c6d"
      url "https://github.com/ghostable-dev/beta/releases/download/v#{version}/ghostable_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ce7161da7077bd6531efc5323cef959c705fee4dcef03bb5cadbe01f403edef"
      url "https://github.com/ghostable-dev/beta/releases/download/v#{version}/ghostable_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c8ed0a306b1498542c57936552da1c5e55be682afb8901dfe869bbb68c7b81fd"
      url "https://github.com/ghostable-dev/beta/releases/download/v#{version}/ghostable_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a1d3de80faa1216143b01633a6d4d02575058e81781dd0eb72783e249dc57e8c"
      url "https://github.com/ghostable-dev/beta/releases/download/v#{version}/ghostable_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ghostable"
  desc "Local-first encrypted environment management CLI"
  homepage "https://github.com/ghostable-dev/beta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghostable"

  # No zap stanza required

end
