# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghostable" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "7138e2ab8ad1d348f1036e8d053cf30d663d84d5932ea552e391c923e4c9a885"
      url "https://github.com/ghostable-dev/beta/releases/download/v#{version}/ghostable_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "576398f02d1ee5aa92ca427049d50ae2f08058943d89afcc0444a5e6a7118a9e"
      url "https://github.com/ghostable-dev/beta/releases/download/v#{version}/ghostable_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "23a785df5ab6d23659941934b21ba4dc7b5ad1d46c0e6036e531e49e5131a2a1"
      url "https://github.com/ghostable-dev/beta/releases/download/v#{version}/ghostable_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb5dd5b6314f1894b4dfa2699eabe84fc0ce99ab8e8b1213d247e37b9d095a48"
      url "https://github.com/ghostable-dev/beta/releases/download/v#{version}/ghostable_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ghostable"
  desc "Local-first encrypted environment management CLI"
  homepage "https://github.com/ghostable-dev/beta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghostable"

  # No zap stanza required

end
