# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghostable" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "38ca627ddad10e267e0efec3161080d86e0b1e2c985cd86afcd84b9454b78274"
      url "https://github.com/ghostable-dev/beta/releases/download/v#{version}/ghostable_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "30d201c74dc31a2c2c099f1816a6500fb37d0c7b6a5492828d4b71d399e54e6c"
      url "https://github.com/ghostable-dev/beta/releases/download/v#{version}/ghostable_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f42a79a6081ce82523ed29ff0dbcad1de7e49b8ec7a8571925d680d67cd3c236"
      url "https://github.com/ghostable-dev/beta/releases/download/v#{version}/ghostable_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2f146455d8b97fc4640d776115290156cd0bd3fa8464c5927726cd39dcd61d0"
      url "https://github.com/ghostable-dev/beta/releases/download/v#{version}/ghostable_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ghostable"
  desc "Local-first encrypted environment management CLI"
  homepage "https://github.com/ghostable-dev/beta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghostable"

  # No zap stanza required

end
